version: "3"
services: 
  node-app:
    ports: 
      - "8080:3000"
    environment: 
      - PORT=3000
  mongo:
    image: mongo
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=thariq
      - MONGO_INITDB_ROOT_PASSWORD=hellodatabase